[pytest]
testpaths = tests
python_files = test_*.py
addopts = -ra --cov=parsers --cov=main --cov=TImetabels --cov=healthcheck --cov=config --cov=states --cov=security --cov=db --cov=keyboards --cov=monitoring --cov=timetable_cache --cov=formatting --cov=rendering --cov=botcore --cov=lk_client --cov=lesson_controller --cov=timetable_service --cov=messages_service --cov=login_service --cov=handlers --cov-report=term:skip-covered
